#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_CODEC_PA_PIN GPIO_NUM_1
#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_4
#define AUDIO_I2S_GPIO_WS GPIO_NUM_7
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_5
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_6
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_8
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_16
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_15
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR
// #define AUDIO_CODEC_ES8311_ADDR 0x30  


#define BUILTIN_LED_GPIO        GPIO_NUM_48
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define TOUCH_BUTTON_GPIO       GPIO_NUM_NC
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

#if CONFIG_BRIDGE_TOUCH_INPUT_ENABLE
#define TOUCH_I2C_SDA_PIN       AUDIO_CODEC_I2C_SDA_PIN
#define TOUCH_I2C_SCL_PIN       AUDIO_CODEC_I2C_SCL_PIN
#define TOUCH_INT_GPIO          GPIO_NUM_17
#define TOUCH_RST_GPIO          GPIO_NUM_18
#define TOUCH_POLL_INTERVAL_MS  30
#define TOUCH_LEFT_ZONE_PERCENT 33
#define TOUCH_MIDDLE_ZONE_PERCENT 34
#define TOUCH_VOLUME_STEP       5
#define TOUCH_DRAG_STEP_PX      16
#define TOUCH_MIN_DRAG_PX       24
#endif


// #define DISPLAY_BACKLIGHT_PIN GPIO_NUM_42
// #define DISPLAY_MOSI_PIN      GPIO_NUM_47
// #define DISPLAY_CLK_PIN       GPIO_NUM_21
// #define DISPLAY_DC_PIN        GPIO_NUM_40
// #define DISPLAY_RST_PIN       GPIO_NUM_45
// #define DISPLAY_CS_PIN        GPIO_NUM_41
//new config lcd
#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_45
#define DISPLAY_MOSI_PIN      GPIO_NUM_11
#define DISPLAY_CLK_PIN       GPIO_NUM_12
#define DISPLAY_DC_PIN        GPIO_NUM_46
#define DISPLAY_RST_PIN       -1
#define DISPLAY_CS_PIN        GPIO_NUM_10

#ifdef CONFIG_LCD_ILI9341_240X320
#define LCD_TYPE_ILI9341_SERIAL
#define DISPLAY_WIDTH   320
#define DISPLAY_HEIGHT  240
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY true
#define DISPLAY_INVERT_COLOR    true
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_BGR
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0
#endif

#ifdef CONFIG_LCD_ILI9341_240X320_NO_IPS
#define LCD_TYPE_ILI9341_SERIAL
#define DISPLAY_WIDTH   320
#define DISPLAY_HEIGHT  240
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY true
#define DISPLAY_INVERT_COLOR    false
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_BGR
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0
#endif

#ifdef CONFIG_LCD_CUSTOM
#define DISPLAY_WIDTH   320
#define DISPLAY_HEIGHT  240
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY true
#define DISPLAY_INVERT_COLOR    true
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_RGB
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0
#endif


// A MCP Test: Control a lamp
#if CONFIG_BRIDGE_TOUCH_INPUT_ENABLE
#define LAMP_GPIO GPIO_NUM_NC
#else
#define LAMP_GPIO GPIO_NUM_18
#endif

#endif // _BOARD_CONFIG_H_
